 function versionamientoBD(db) {
    db.version(34).stores({
        Sincronizacion: '++id, nombre', // Primary key and indexed props
        upgds: '_id,[COD_PRE+COD_SUB],COD_PRE,ACT_SIV',
        TipoEvento: '_id,cod_eve,descripcionLista,exa_lab',
        TablaTipoEvento: '_id,cod_eve,[cl_ordenGrupo+cl_ordenFormulario],cl_inactivo',
        OrdenCamposBDUA: '_id',
        Funcionalidades: '_id,cod_eve',
        FuncionalidadesAfectantes: '_id,cod_eve',
        Validaciones: '_id,cod_eve',
        ValidacionesAfectantes: '_id,cod_eve',
        Paises: '_id',
        Departamentos: '_id,CodNumPais',
        Municipios: '_id,[Cod_pais+Cod_Depto],Cod_mun,Cod_Depto,Cod_pais', // Primary key and indexed props
        cie10: '_id,codigoItem,codigoItem2',
        Calendario: '_id,vigencia',
        ajustes: '_id,codigoItem',
        ajustesColectivos: '_id,codigoItem',
        sectores: '_id,codigoItem1,codigoItem2',
        veredas: '_id,codigoItem,codigoItem1,codigoItem2,codigoItem3',
        clasifi_cas: '_id,codigoItem',
        Aseguradoras: '_id,regimen',
        EnfermedadesHuerfanas: '_id,CONFIRMADO,COD_ENFERM',
        SustanciasIntoxicantes: '_id,VALOR_ASOC,COD_EVE',
        Ocupaciones: '_id,activo,Menores,Cod_ocu',
        GruposEtnicos: '_id',
        ajustesLaboratorios: '_id',
        Resultados: '_id',
        Agentes: '_id',
        Pruebas: '_id,codigoItem',
        Req_fec_exa: '_id',
        Req_fec_rec: '_id',
        Muestras: '_id,codigoItem',
        ElementosLaboratorio: '_id,cod_eve',
        EventosColectivosSemana: '++_id, SyncError,Cod_eve,Cod_pre,Ano,Mes,Semana,Municipio,Cod_sub',
        EventosColectivosMes: '++_id, SyncError,Cod_eve,Cod_pre,Ano,Mes,Semana,Municipio,Cod_sub',
        Brotes: '++_id, SyncError,COD_EVE,COD_PRE,ANO,SEMANA,COD_MUN,COD_SUB',
        fn_unidades: '_id',
        fm_grados: '_id',
        agentes_etas:'_id,codigoItem',
        Eventos: '++_id, SyncError, [Cod_eve+Semana+Año+Tip_ide+Num_ide+Cod_pre+Cod_sub], [Cod_eve+Semana+Año+Tip_ide+Num_ide],Cod_eve,Num_ide,Pri_nom,Seg_nom,Pri_ape,Seg_ape,Cod_pre,Ano,Semana,Nom_dil_fi,Cod_mun_o,Cod_mun_r,Cod_sub',
        AnalisisLaboratorio: '++_id,SyncError',
        Uci: '_id,Cod_pre',
        Carceles:'_id',
        tbCups:'_id,codigoItem,descripcionLista',
        Antibioticos: '_id',
        organos_espacio:'_id,codigoItem',
        pruebasenfermedadeshuerfanas:'_id,IDPRUEBA',
        OMS_Zscore_Peso_talla:'_id, [height+sexo]',//[height+sexo+edad_inicial+edad_final], 
        OMS_Zscore_Talla_Edad:'_id, [month+sexo]',
        ElementosUnicosFormularios:'_id,cod_eve',
        LookupsTable:'_id,codigoItem,codigoItem1,codigoItem2,codigoItem3,codigoItem4,codigoItem5,[codigoItem1+codigoItem2+codigoItem3]',
        RelacionEventosLaboratorios: '++_id,idEventoOffline,idEventoOnline',
    });
}